In [11]:
from wtn_mdt.data_loader import data_path
import pandas as pd
import numpy as np

# Standardized and Clean inputs

In [12]:
merged_table = pd.read_csv(data_path('merged_table_3.csv'))
test_with_reschart = pd.read_csv(data_path('test_with_reschart.csv'))

In [13]:
final_column_order = ['WellID', 'zone', 'Category', 'xclass', 'GR', 'log_RT', 'DEN', 'NPHI']

In [14]:
# Some well has 2 blocks ditch the effort of filling in block
# one could fill it by depth though
# # patch blocks
# def build_block_dict(well_ids, blocks):
#     d = {}
#     def is_blank(block):
#         return not isinstance(block, str) or block==''
        
#     for well_id, block in zip(well_ids, blocks):
#         if well_id in d:
#             if not is_blank(block) and d[well_id] != block:
#                 # make sure no conflict
#                 print(f'Hmm, {well_id}, {block} {d[well_id]}')
#         else:
#             if not is_blank(block):
#                 d[well_id] = block
#     unique_well_ids = well_ids.unique()
#     # ensure every well has a block
#     for well in unique:
#         if well not in d:
#             print(f"{well} not found.")
#     return d
        
# build_block_dict(merged_table.WellID, merged_table.Block)

In [15]:
reduced_test  = test_with_reschart[['WellID', 'Category', 'GR', 'RT', 'DEN', 'NPHI']]
def get_xclass(category):
    return 1 if category=='Normal' else 0    
reduced_test['xclass'] = reduced_test.Category.map(get_xclass)
def get_zone(well_id):
    assert len(well_id) > 3
    return well_id[:3]
reduced_test['zone'] = reduced_test.WellID.map(get_zone)
reduced_test['log_RT'] = np.log(reduced_test.RT)
reduced_test= reduced_test[final_column_order]
reduced_test.dropna()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

       WellID zone Category  xclass         GR    log_RT       DEN      NPHI
0     KMG-A05  KMG   Normal       1  61.816006  0.396843  2.233575  0.280175
1     KMG-A05  KMG   Normal       1  47.363773  1.011730  2.394488  0.148107
2     KMG-A05  KMG      Dry       0  55.203945 -0.096017  2.294666  0.254202
3     KMG-A05  KMG   Normal       1  58.467442  0.683599  2.274010  0.280277
4     KMG-A05  KMG   Normal       1  49.301380  0.656314  2.287699  0.268446
...       ...  ...      ...     ...        ...       ...       ...       ...
7147  WTN-A21  WTN   Normal       1  44.978325 -0.026603  2.191675  0.266541
7148  WTN-A21  WTN   Normal       1  51.862110  0.826672  2.309331  0.173542
7149  WTN-A21  WTN   Normal       1  42.119560  0.246984  2.214764  0.225576
7150  WTN-A21  WTN   Normal       1  65.298660  0.000514  2.221059  0.326785
7151  WTN-A21  WTN      Dry       0  58.899601  0.802467  2.386394  0.176494

[7032 rows x 8 columns]

In [16]:
merged_table.columns

Index(['SubBlock', 'Block', 'WellID', 'ST', 'RunNo', 'TestNo', 'RunningDate',
       'Depth', 'DepthTVDSS', 'Reservoir', 'Marker', 'HydroctaticBefore',
       'HydroctaticAfter', 'FormationPressure', 'SG_EMW', 'Mobility',
       'Temperature', 'Comment', 'Sample', 'Fluid', 'Category', 'WellID2',
       'DEPTH', 'GR', 'RHOB', 'RT', 'NPHI', 'PORC', 'SAND', 'FCOL',
       'ActualPerf', 'WELL_ID', 'interpolated', 'RXO', 'CALI', 'SWE', 'PERM',
       'VSH', 'LITH', 'BS', 'RMED', 'IC5', 'C1', 'C3', 'C2', 'IC4', 'PHIE',
       'TG (%)', 'DT', 'TENS', 'PHIT', 'RES', 'NC4', 'CO2', 'NC5', 'ROP',
       'Core Facies', 'PlanPerf', 'TG', 'GR_Smooth', 'NPHI_Smooth',
       'RT_Smooth', 'RHOB_Smooth'],
      dtype='object')

In [17]:
reduced_merge = merged_table[['WellID', 'Category', 'GR', 'RT', 'RHOB', 'NPHI' ]]
reduced_merge['DEN'] = reduced_merge['RHOB']
print(reduced_merge.columns)
reduced_merge['xclass'] = reduced_merge.Category.map(get_xclass)
reduced_merge['zone'] = reduced_merge.WellID.map(get_zone)
reduced_merge['log_RT'] = np.log(reduced_merge.RT)
reduced_merge = reduced_merge[final_column_order]
reduced_merge = reduced_merge.dropna()

Index(['WellID', 'Category', 'GR', 'RT', 'RHOB', 'NPHI', 'DEN'], dtype='object')

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py:679: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [18]:
reduced_merge.dropna()

       WellID zone Category  xclass         GR    log_RT       DEN      NPHI
0     LKU-A08  LKU   Normal       1  65.915863  2.152699  2.173795  0.212531
1     LKU-A08  LKU   Normal       1  67.053558  2.297950  2.189971  0.248978
2     LKU-A08  LKU   Normal       1  75.654899  2.826069  2.115781  0.164317
3     LKU-A08  LKU   Normal       1  64.110095  3.931080  2.150466  0.305364
4     LKU-A08  LKU   Normal       1  51.243954  3.374626  2.114616  0.317336
...       ...  ...      ...     ...        ...       ...       ...       ...
9738  WTN-C14  WTN   Normal       1  62.391300  0.244279  2.373900  0.209567
9739  WTN-C14  WTN   Normal       1  52.938202 -0.362981  2.259700  0.252772
9740  WTN-C14  WTN      Dry       0  80.876981  2.292660  2.587900  0.128779
9741  WTN-C14  WTN   Normal       1  51.330200  1.054312  2.361400  0.176027
9742  WTN-C14  WTN   Normal       1  49.553661  0.136941  2.337360  0.202942

[9033 rows x 8 columns]

In [19]:
all_data = pd.concat([reduced_test, reduced_merge])
all_data = all_data.sort_values(by='WellID').reset_index().drop('index', axis=1)

In [20]:
all_data.to_excel(data_path('all_data.xlsx'), index=False)